### PR TITLE
cairo error->exit(1) and replace Kaiser window with Hanning

### PR DESCRIPTION
**Pull request by martinwguy**
The most significant of these is to fix issue #15 by changing window function.
An alternative would be an option to select windowing function, but Hanning seems to work best.

### CODE REVIEW

**Comment by erikd** [comment]
Can we separate out the Cairo error handling from the windowing changes?

And for the windowing, how about providing an option to choose between windows so that I (and others) can compare and contrast more easily?

**Comment by martinwguy** [comment]
Thanks, I'll sort that out.

**Comment by martinwguy** [comment]
OK, I've made a new pull request for the error-handling change.
Now that I've made the windowing function selectable, if I submit a second pull request, it includes both commits though. How should I proceed to suggest several independent changes simultaneously?
Can you cherry-pick it from 87f784341760babf1a3ad33b6822e82136ae1ad7 ?

**Comment by erikd** [comment]
Got it. Thanks.

**Pull request closed without merging**
