### PR TITLE
Several fixes to jackplay

### PR DESCRIPTION
**Pull request by falkTX**
1. Output silence when failing to read on time or file ends
2. Deactivate client before waiting for close
3. Handle SIGINT/SIGTERM

### CODE REVIEW

**Comment by erikd** [comment]
Looks good. Do you mind squashing those two into a single commit?

**Comment by falkTX** [comment]
not at all, I'll do that tomorrow.

**Comment by erikd** [comment]
Never mind. Did it myself and added few little whitespace fixes.

Thanks again!

**Comment by falkTX** [comment]
ah cool, thanks.
glad to be useful.

**Pull request closed without merging**
